# Generated by Django 5.2.17 on 2026-08-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="datasheet",
            field=models.FileField(blank=True, upload_to="datasheets/"),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="0-5, rendered by the Rating component on the detail page.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        default="building-2",
                        help_text="Lucide icon name rendered next to the node.",
                        max_length=40,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="showcase.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
