# Generated by Django 5.2.17 on 2026-09-05 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0002_product_available_from_product_datasheet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=80)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=5, help_text="0-5."),
                ),
                (
                    "submitted_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="showcase.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "ordering": ["-submitted_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='e.g. "Blue, medium tip" or "120x60cm".',
                        max_length=100,
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=40, unique=True, verbose_name="SKU"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Sellable"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="showcase.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "variant",
                "ordering": ["label"],
            },
        ),
    ]
