# Generated by Django 5.2.18 on 2026-10-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0003_productreview_productvariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Describes the photo for screen readers. Falls back to the product name.",
                        max_length=150,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="showcase.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "ordering": ["position", "pk"],
            },
        ),
    ]
