#!/usr/bin/env node
/*
 * Generates wise_core/static/wise_core/css/md3-palettes.css - the Material 3
 * *reference* palettes (`--md-ref-palette-*`) behind every color in the
 * design system.
 *
 *     npm run build:palettes      (then `npm run build:css`)
 *
 * Uses Google's own @material/material-color-utilities (the library behind
 * Material Theme Builder) with the classic M3 "core palette" recipe, so the
 * baseline seed #6750A4 reproduces the published M3 baseline scheme exactly
 * (primary #6750A4, secondary #625B71, tertiary #7D5260, ...):
 *
 *   primary          seed hue, chroma max(48, seed chroma)
 *   secondary        seed hue, chroma 16
 *   tertiary         seed hue + 60deg, chroma 24
 *   neutral          seed hue, chroma 4
 *   neutral-variant  seed hue, chroma 8
 *   error            hue 25, chroma 84
 *   success/warning  M3 "custom colors": a fixed seed harmonized toward the
 *                    source color, so they stay green/amber but sit in the
 *                    same family as the palette.
 *
 * The *system* tokens (`--md-sys-color-primary` = primary40 in light,
 * primary80 in dark, ...) live in tokens.css and only point at these tones,
 * which is why a palette switch never needs its own dark-mode block.
 *
 * To rebrand: add or edit an entry in PALETTES below and re-run.
 */
import {writeFileSync} from 'node:fs'
import {dirname, resolve} from 'node:path'
import {fileURLToPath} from 'node:url'
import {
    Blend,
    Hct,
    TonalPalette,
    argbFromHex,
    hexFromArgb,
} from '@material/material-color-utilities'

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../wise_core/static/wise_core/css/md3-palettes.css')

// `null` selector key = the default palette (no data-palette attribute).
const PALETTES = [
    {name: null, label: 'baseline (M3 default)', seed: '#6750A4'},
    {name: 'green', label: 'green', seed: '#386A20'},
    {name: 'blue', label: 'blue', seed: '#0061A4'},
    {name: 'amber', label: 'amber', seed: '#8B5000'},
]

const SUCCESS_SEED = '#2E7D32'
const WARNING_SEED = '#B26A00'

// Neutral-only overrides for the data-bg axis.
const BACKGROUNDS = [
    {name: 'warm', hue: 70, chroma: 6},
    {name: 'cool', hue: 250, chroma: 6},
]

const KEY_TONES = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 98, 99, 100]
const NEUTRAL_TONES = [0, 4, 6, 10, 12, 17, 20, 22, 24, 25, 30, 35, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100]

function keyPalette(argb) {
    const hct = Hct.fromInt(argb)
    return TonalPalette.fromHueAndChroma(hct.hue, Math.max(48, hct.chroma))
}

function lines(name, palette, tones) {
    return tones.map((t) => `    --md-ref-palette-${name}${t}: ${hexFromArgb(palette.tone(t))};`)
}

function neutralLines(hue, chroma) {
    return [
        ...lines('neutral', TonalPalette.fromHueAndChroma(hue, chroma), NEUTRAL_TONES),
        ...lines('neutral-variant', TonalPalette.fromHueAndChroma(hue, chroma * 2), KEY_TONES),
    ]
}

function paletteBlock({name, label, seed}) {
    const source = argbFromHex(seed)
    const hct = Hct.fromInt(source)
    const selector = name ? `:root[data-palette="${name}"]` : ':root'
    const body = [
        `    --md-source-color: ${seed.toLowerCase()};`,
        ...lines('primary', keyPalette(source), KEY_TONES),
        ...lines('secondary', TonalPalette.fromHueAndChroma(hct.hue, 16), KEY_TONES),
        ...lines('tertiary', TonalPalette.fromHueAndChroma((hct.hue + 60) % 360, 24), KEY_TONES),
        ...lines('error', TonalPalette.fromHueAndChroma(25, 84), KEY_TONES),
        ...lines('success', keyPalette(Blend.harmonize(argbFromHex(SUCCESS_SEED), source)), KEY_TONES),
        ...lines('warning', keyPalette(Blend.harmonize(argbFromHex(WARNING_SEED), source)), KEY_TONES),
        ...neutralLines(hct.hue, 4),
    ]
    return `/* ${label} - seed ${seed} */\n${selector} {\n${body.join('\n')}\n}`
}

function backgroundBlock({name, hue, chroma}) {
    return `/* data-bg="${name}" - neutral hue ${hue}, chroma ${chroma} */\n` +
        `:root[data-bg="${name}"] {\n${neutralLines(hue, chroma).join('\n')}\n}`
}

const header = `/* ══════════════════════════════════════════════════════════════════════
   GENERATED by scripts/generate_m3_palettes.mjs - do not edit by hand.

   Material 3 reference palettes (--md-ref-palette-<palette><tone>). The
   system color roles in tokens.css (--md-sys-color-*) point at these tones;
   components never read them directly. data-bg blocks come last so they
   override the palette's own neutrals at equal specificity.
   ══════════════════════════════════════════════════════════════════════ */`

writeFileSync(OUT, [header, ...PALETTES.map(paletteBlock), ...BACKGROUNDS.map(backgroundBlock)].join('\n\n') + '\n')
console.log(`wrote ${OUT}`)
